### ISSUE TITLE
Exception while collecting markers

### ISSUE THREAD

**Issue by ShDis** [TechnicJelle/BlueMapSignExtractor#36]
Purpur 1.20.2, Blue Map 3.17
```
[00:02:15] [Craft Scheduler Thread - 5 - BlueMap/WARN]: [BlueMapSignExtractor] New version available: v1.2 (current: v1.3-PREVIEW2)
[00:02:15] [Craft Scheduler Thread - 5 - BlueMap/WARN]: [BlueMapSignExtractor] Download it at https://github.com/TechnicJelle/BlueMapSignExtractor/releases/latest
[00:02:15] [Craft Scheduler Thread - 5 - BlueMap/INFO]: [BlueMapAreaControl] BlueMapAreaControl enabled!
[00:02:15] [Craft Scheduler Thread - 5 - BlueMap/INFO]: [BlueMapAreaControl] Loading existing configs
[00:02:15] [Craft Scheduler Thread - 5 - BlueMap/INFO]: [BlueMapAreaControl] Loading config for map: world
[00:02:15] [Craft Scheduler Thread - 2 - BlueMapSignExtractor/INFO]: [BlueMapSignExtractor] World "world": Extracting signs into markers...
[00:02:15] [Craft Scheduler Thread - 5 - BlueMap/INFO]: [BlueMapAreaControl] Loading config for map: world_the_end
[00:02:15] [Craft Scheduler Thread - 5 - BlueMap/INFO]: [BlueMap] Loaded!
[01:37:56] [Craft Scheduler Thread - 2 - BlueMapSignExtractor/WARN]: [BlueMapSignExtractor] Plugin BlueMapSignExtractor v1.3-PREVIEW2 generated an exception while executing task 67
java.lang.NullPointerException: null
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
	at java.util.ImmutableCollections$SetN.contains(ImmutableCollections.java:937) ~[?:?]
	at com.technicjelle.bluemapsignextractor.common.Chunk.isFinished(Chunk.java:20) ~[BlueMapSignExtractor-1.3-PREVIEW2.jar:?]
	at com.technicjelle.bluemapsignextractor.common.Chunk.isGenerated(Chunk.java:31) ~[BlueMapSignExtractor-1.3-PREVIEW2.jar:?]
	at com.technicjelle.bluemapsignextractor.common.MCARegion.getBlockEntities(MCARegion.java:112) ~[BlueMapSignExtractor-1.3-PREVIEW2.jar:?]
	at com.technicjelle.bluemapsignextractor.common.Core.fillMarkerSetFromRegionFile(Core.java:57) ~[BlueMapSignExtractor-1.3-PREVIEW2.jar:?]
	at com.technicjelle.bluemapsignextractor.common.Core.lambda$loadMarkerSetFromWorld$2(Core.java:42) ~[BlueMapSignExtractor-1.3-PREVIEW2.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at com.technicjelle.bluemapsignextractor.common.Core.loadMarkerSetFromWorld(Core.java:42) ~[BlueMapSignExtractor-1.3-PREVIEW2.jar:?]
	at com.technicjelle.bluemapsignextractor.common.Core.addMarkersToBlueMapWorld(Core.java:24) ~[BlueMapSignExtractor-1.3-PREVIEW2.jar:?]
	at com.technicjelle.bluemapsignextractor.BlueMapSignExtractor.loadMarkersFromWorlds(BlueMapSignExtractor.java:67) ~[BlueMapSignExtractor-1.3-PREVIEW2.jar:?]
	at com.technicjelle.bluemapsignextractor.BlueMapSignExtractor.lambda$new$0(BlueMapSignExtractor.java:50) ~[BlueMapSignExtractor-1.3-PREVIEW2.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by TechnicJelle** [comment]
_Huh_...
Somewhere, there is a chunk that does not have a status.

The problem lies here:
```java
default boolean isFinished() {
	return FINISHED_STATUSES.contains(getStatus());
}
```
It's trying to see if the chunk's status is finished, but the `getStatus()` call is returning `null` for some reason!

I'll attach a version of the plugin with extra logging, so we can find the exact region file and the exact chunk inside the region file that is this broken.
Could you please send the region file that is causing this problem here, so I can inspect it and think up a good solution for cases like these?

[BlueMapSignExtractor-1.3-PREVIEW3.jar.zip](https://github.com/TechnicJelle/BlueMapSignExtractor/files/14475349/BlueMapSignExtractor-1.3-PREVIEW3.jar.zip)

**Comment by ShDis** [comment]
Launched. I'll be back tomorrow with the results. Thanks for your work (7 minutes to patch since opening issue o-0)

**Comment by TechnicJelle** [comment]
I'm eagerly awaiting the result!
And keep in mind this isn't a patch, this is just extra logging, so we may find out more information about the cause.

**Comment by ShDis** [comment]
There were a lot of errors in the log (almost 1mb), mostly with chunks older than 1.13.2. 
But after two hours 6000+ signs were observable via site, that's awesome. Beside framerate in browser, it's like 4-5 frames/second :)

The error with null status could be connected with part of the world contained some old 1.18 snapshot chunks:
```
[04:03:32] [Craft Scheduler Thread - 10 - BlueMapSignExtractor/INFO]: [BlueMapSignExtractor] World "world": Extracting signs into markers...
[04:03:32] [Craft Scheduler Thread - 5 - BlueMap/INFO]: [BlueMapAreaControl] Loading config for map: world_the_end
[04:03:32] [Craft Scheduler Thread - 5 - BlueMap/INFO]: [BlueMap] Loaded!
[05:40:57] [Craft Scheduler Thread - 10 - BlueMapSignExtractor/ERROR]: [BlueMapSignExtractor] Error reading region file
java.io.IOException: NullPointerException in chunk 20, 11 in region file C:\2s2d\.\world\region\r.282.253.mca
		Chunk class: ChunkClass { DataVersion: 2840 -> Loader: MC_1_18_2_Chunk }
	at com.technicjelle.bluemapsignextractor.common.MCARegion.getBlockEntities(MCARegion.java:115) ~[BlueMapSignExtractor-1.3-PREVIEW3.jar:?]
	at com.technicjelle.bluemapsignextractor.common.Core.fillMarkerSetFromRegionFile(Core.java:57) ~[BlueMapSignExtractor-1.3-PREVIEW3.jar:?]
	at com.technicjelle.bluemapsignextractor.common.Core.lambda$loadMarkerSetFromWorld$2(Core.java:42) ~[BlueMapSignExtractor-1.3-PREVIEW3.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at com.technicjelle.bluemapsignextractor.common.Core.loadMarkerSetFromWorld(Core.java:42) ~[BlueMapSignExtractor-1.3-PREVIEW3.jar:?]
	at com.technicjelle.bluemapsignextractor.common.Core.addMarkersToBlueMapWorld(Core.java:24) ~[BlueMapSignExtractor-1.3-PREVIEW3.jar:?]
	at com.technicjelle.bluemapsignextractor.BlueMapSignExtractor.loadMarkersFromWorlds(BlueMapSignExtractor.java:67) ~[BlueMapSignExtractor-1.3-PREVIEW3.jar:?]
	at com.technicjelle.bluemapsignextractor.BlueMapSignExtractor.lambda$new$0(BlueMapSignExtractor.java:50) ~[BlueMapSignExtractor-1.3-PREVIEW3.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.20.2.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?]
	at java.util.ImmutableCollections$SetN.contains(ImmutableCollections.java:937) ~[?:?]
	at com.technicjelle.bluemapsignextractor.common.Chunk.isFinished(Chunk.java:20) ~[BlueMapSignExtractor-1.3-PREVIEW3.jar:?]
	at com.technicjelle.bluemapsignextractor.common.Chunk.isGenerated(Chunk.java:31) ~[BlueMapSignExtractor-1.3-PREVIEW3.jar:?]
	at com.technicjelle.bluemapsignextractor.common.MCARegion.getBlockEntities(MCARegion.java:113) ~[BlueMapSignExtractor-1.3-PREVIEW3.jar:?]
	... 22 more
```

**Comment by ShDis** [comment]
Region file causing the error
[r.282.253.zip](https://github.com/TechnicJelle/BlueMapSignExtractor/files/14484720/r.282.253.zip)

**Comment by TechnicJelle** [comment]
Aha, this was surprisingly simple to diagnose! :D

This is the internal data of the chunk:
![image](https://github.com/TechnicJelle/BlueMapSignExtractor/assets/22576047/98be31b6-de6c-4251-8f91-dc3279f2c8a9)
As you can see, it's inside a Level section.

And only inside that Level section, is the actual Status:
![image](https://github.com/TechnicJelle/BlueMapSignExtractor/assets/22576047/1775a88a-139e-44f7-b951-ac648bc0a51b)

This Level section is how it used to be before 1.18:
https://github.com/TechnicJelle/BlueMapSignExtractor/blob/1e1d96a48d0639cb2f41e0cf675f49dd28b5fb05/src/main/java/com/technicjelle/bluemapsignextractor/versions/MC_1_17_1/MC_1_17_1_Chunk.java#L8-L18

My 1.17 chunk parser takes the Level section into account, while my 1.18 parser does not:
https://github.com/TechnicJelle/BlueMapSignExtractor/blob/1e1d96a48d0639cb2f41e0cf675f49dd28b5fb05/src/main/java/com/technicjelle/bluemapsignextractor/versions/MC_1_18_2/MC_1_18_2_Chunk.java#L9-L14

But the Data Version of this chunk (2840) was making the plugin use the 1.18 parser, instead of the 1.17 one:
https://github.com/TechnicJelle/BlueMapSignExtractor/blob/1e1d96a48d0639cb2f41e0cf675f49dd28b5fb05/src/main/java/com/technicjelle/bluemapsignextractor/common/ChunkClass.java#L39-L53

It is extremely tedious to go through every single snapshot changelog to see where exactly things changed, so I just eyeballed these cut-off points.
Clearly they need more tweaking, which I shall do!
Give me a moment...

**Comment by TechnicJelle** [comment]
Oh, I actually did find the exact snapshot in which they did the cleanup just now!
It's [21w34a](https://minecraft.wiki/w/Java_Edition_21w43a), with Data Version 2844!

This means I can now pinpoint the exact cut-off point for at least this change!
Thank you very much for pointing me in the right direction!

**Comment by TechnicJelle** [comment]
In e800afc3ab60f1859439158f83e09f420a70709d, I changed the way I log stuff, which should hopefully reduce the large amount of logs.
I haven't implemented that it only logs an error/warning once, yet, though.
(I am kind of hoping it's not necessary any more, with the change I just made)

If you're up for it, could you try this new build?

[BlueMapSignExtractor-1.3-PREVIEW4.jar.zip](https://github.com/TechnicJelle/BlueMapSignExtractor/files/14488142/BlueMapSignExtractor-1.3-PREVIEW4.jar.zip)

**Comment by ShDis** [comment]
Thanks for the detailed explanation! 
I'll test the new build but it'll take about two hours to collect markers, so there's a small chance I won't be back until tomorrow.

**Comment by ShDis** [comment]
Looks good, but it's still about ~23mb log of warnings.

![image](https://github.com/TechnicJelle/BlueMapSignExtractor/assets/71232121/de41238f-d8cc-4c17-b2c1-b956f15d6079)

**Comment by TechnicJelle** [comment]
I think I'll add a config option to suppress warnings about old/incompatible chunks...
