### ISSUE TITLE
Failed to load addon 'plugins\BlueMap\addons\BlueMapSignExtractor-1.3.jar'

### ISSUE THREAD

**Issue by SavageCore** [TechnicJelle/BlueMapSignExtractor#61]
Unable to load this addon, SpawnMarker works fine as does the map generally. Let me know if you need more information!

```
[BlueMap] Failed to load addon 'plugins\BlueMap\addons\BlueMapSignExtractor-1.3.jar'
de.bluecolored.bluemap.common.addons.AddonException: No bluemap.addon.json found in 'plugins\BlueMap\addons\BlueMapSignExtractor-1.3.jar'
        at BlueMap-5.3.jar/de.bluecolored.bluemap.common.addons.Addons.tryLoadAddon(Addons.java:76) ~[BlueMap-5.3.jar:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
        at java.base/java.util.Iterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Unknown Source) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:?]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:?]
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:?]
        at BlueMap-5.3.jar/de.bluecolored.bluemap.common.addons.Addons.tryLoadAddons(Addons.java:67) ~[BlueMap-5.3.jar:?]
        at BlueMap-5.3.jar/de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:127) ~[BlueMap-5.3.jar:?]
        at BlueMap-5.3.jar/de.bluecolored.bluemap.common.plugin.Plugin.load(Plugin.java:113) ~[BlueMap-5.3.jar:?]
        at BlueMap-5.3.jar/de.bluecolored.bluemap.common.plugin.Plugin.reload(Plugin.java:489) ~[BlueMap-5.3.jar:?]
        at BlueMap-5.3.jar/de.bluecolored.bluemap.common.plugin.commands.Commands.lambda$reloadCommand$5(Commands.java:415) ~[BlueMap-5.3.jar:?]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
```

Versions:

`BlueMap-5.3.jar`
`BlueMapSignExtractor-1.3.jar`
`paper-1.21.1-52.jar`

**Comment by TechnicJelle** [comment]
BlueMap Sign Extractor is (currently) a normal Paper plugin, so it goes in your plugins folder.
That `BlueMap/addons/` folder is for BlueMap Native addons. Currently, there are only two of those (as far as we know, anyway). Spawn Marker is one of them, so that's why that one is working there.

I am actually working on porting BlueMap Sign Extractor over to that, but it's been taking a while, due to being very busy.

Please let me know if you got it working by moving it to the plugins folder, so I can close this issue :)

**Comment by SavageCore** [comment]
Oh yeah, silly me! Thanks
